version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
